<?php

/**
 * @file
 * Contains site_location.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function site_location_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the site_location module.
    case 'help.page.site_location':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module provide admin to configure: location, timezone and also able to view current time and location block.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function site_location_theme($existing, $type, $theme, $path) {
  return [
    'site_location_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}

/*
 * get Timezone
 */
function getTimeZone() {
  return [
    'America/Chicago'=> t('America/Chicago'),
    'America/New_York'=> t('America/New_York'),
    'Asia/Tokyo'=> t('Asia/Tokyo'),
    'Asia/Dubai'=> t('Asia/Dubai'),
    'Asia/Kolkata'=> t('Asia/Kolkata'),
    'Europe/Amsterdam'=> t('Europe/Amsterdam'),
    'Europe/Oslo'=> t('Europe/Oslo'),
    'Europe/London'=> t('Europe/London')
  ];
}
